apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.app_name }}
  labels:
    app: ${{ values.app_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.app_name }}
  template:
    metadata:
      labels:
        app: ${{ values.app_name }}
    spec:
      containers:
      - name: ${{ values.app_name }}
        image: udaytc/${{ values.app_name }}:v1
        ports:
        - containerPort: 5000
