name: Build Docker Image

on:
  push:
    paths:
      - ${{ values.app_name }}/**  # Gatilho para alterações no diretório uday_app
    branches:
      - main  # Gatilho para branch principal

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Definir a tag da imagem (SHA reduzido)
        run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ '${{ secrets.DOCKERHUB_USERNAME }}' }}
          password: ${{ '${{ secrets.DOCKERHUB_TOKEN }}' }}

      - name: Build da imagem apenas com a tag da versão
        run: |
          docker build -t ${{ '${{ secrets.DOCKERHUB_USERNAME }}' }}/${{ values.app_name }}:${IMAGE_TAG} .

      - name: Push da imagem
        run: docker push ${{ '${{ secrets.DOCKERHUB_USERNAME }}' }}/${{ values.app_name }}:${IMAGE_TAG}
