apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: flask-service
  title: Template Flask Service
  description: Template para deploy do app Flask service
spec:
  owner: devops
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Fill in some steps
      required:
        - name
        - environment
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        environment:
          title: Environment
          type: string
          description: Environment of the component
          enum:
            - production
            - staging
            - development
          default: development
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group

    - title: Choose a location
      required:
        - repo
      properties:
        repo:
          title: Repository Name
          type: string
          description: Name of the repository to be created

  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        targetPath: '.'
        values:
          app_name: ${{ parameters.name }}
          app_env: ${{ parameters.environment }}
          app_owner: ${{ parameters.owner }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.name }}
        repoUrl: github.com?owner=uday-platform-idp-org&repo=${{ parameters.repo }}
        defaultBranch: 'main'
        initializeWithReadme: true
        repoVisibility: public

    - id: init-commit
      name: Commit inicial
      action: run:script
      input:
        script: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/uday-platform-idp-org/${{ parameters.repo }}.git
          cd ${{ parameters.repo }}
          echo "# ${{ parameters.name }}" > README.md
          git config user.email "backstage@uday.com"
          git config user.name "Backstage Bot"
          git add .
          git commit -m "Initial commit"
          git push origin main

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
